CitasMedicas.Web/Controllers/DoctorController.cs
using CitasMedicas.Web.Models;
using CitasMedicas.Web.Models.Doctor;
using CitasMedicas.Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CitasMedicas.Web.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorService _doctorService;
        public DoctorController(IDoctorService doctorService)
        {
            _doctorService = doctorService;
        }

        [HttpGet]
        public async Task<IActionResult> DoctorIndex()
        {
            List<DoctorDto>? doctorList = new();
            ResponseDto? responseDto = await _doctorService.GetDoctorsAsync();
            if(responseDto != null && responseDto.IsSuccess)
            {
                doctorList = JsonConvert.DeserializeObject<List<DoctorDto>>(Convert.ToString(responseDto.Result));
            }
            else
            {
                TempData["error"] = responseDto?.Message ?? "Error al obtener los doctores.";
            }
            return View(doctorList);
        }

        #region Create Doctor

        [HttpGet]
        public async Task<IActionResult> DoctorCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DoctorCreate(CreateDoctorDto doctorDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto responseDto = await _doctorService.CreateDoctorAsync(doctorDto);
                if (responseDto != null && responseDto.IsSuccess)
                {
                    TempData["success"] = responseDto.Message ?? "Doctor creado correctamente.";
                    return RedirectToAction(nameof(DoctorIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message ?? "Error al crear el doctor.";
                }
            }
            return View(doctorDto);
        }

        #endregion

        #region Update Patient
        [HttpGet]
        public async Task<IActionResult> DoctorUpdate(int doctorId)
        {
            ResponseDto? responseDto = await _doctorService.GetDoctorByIdAsync(doctorId);
            if (responseDto != null && responseDto.IsSuccess)
            {
                DoctorDto? doctorDto = JsonConvert.DeserializeObject<DoctorDto>(Convert.ToString(responseDto.Result));
                if (doctorDto != null)
                {
                    UpdateDoctorDto updateDoctorDto = new()
                    {
                        DoctorId = doctorDto.DoctorId,
                        Name = doctorDto.Name,
                        LastName = doctorDto.LastName,
                        PhoneNumber = doctorDto.PhoneNumber,
                        Email = doctorDto.Email,
                        SpecialtyId = doctorDto.SpecialtyId
                    };
                    return View(updateDoctorDto);
                }
            }
            TempData["error"] = responseDto?.Message ?? "Error al obtener el doctor.";
            return RedirectToAction(nameof(DoctorIndex));
        }

        [HttpPost]
        public async Task<IActionResult> DoctorUpdate(UpdateDoctorDto doctorDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto responseDto = await _doctorService.UpdateDoctorAsync(doctorDto);
                if (responseDto != null && responseDto.IsSuccess)
                {
                    TempData["success"] = responseDto.Message ?? "Doctor actualizado correctamente.";
                    return RedirectToAction(nameof(DoctorIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message ?? "Error al actualizar el doctor.";
                }
            }
            return View(doctorDto);
        }

        #endregion
    }
}

CitasMedicas.Web/Controllers/PatientController.cs
using CitasMedicas.Web.Models;
using CitasMedicas.Web.Models.Patient;
using CitasMedicas.Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CitasMedicas.Web.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientService _patientService;
        public PatientController(IPatientService patientService)
        {
            _patientService = patientService;
        }

        [HttpGet]
        public async Task<IActionResult> PatientIndex()
        {
            List<PatientDto>? patientList = new();
            ResponseDto? responseDto = await _patientService.GetPatientsAsync();

            if(responseDto != null && responseDto.IsSuccess)
            {
                patientList = JsonConvert.DeserializeObject<List<PatientDto>>(Convert.ToString(responseDto.Result));
            }
            else
            {
                TempData["error"] = responseDto?.Message ?? "Error al obtener los pacientes.";
            }

            return View(patientList);
        }

        #region Create Patient

        [HttpGet]
        public async Task<IActionResult> PatientCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PatientCreate(CreatePatientDto patientDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto responseDto = await _patientService.CreatePatientAsync(patientDto);
                if (responseDto != null && responseDto.IsSuccess)
                {
                    TempData["success"] = responseDto.Message ?? "Paciente creado correctamente.";
                    return RedirectToAction(nameof(PatientIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message ?? "Error al crear el paciente.";
                }
            }

            return View(patientDto);
        }

        #endregion

        #region Update Patient

        [HttpGet]
        public async Task<IActionResult> PatientEdit(int patientId)
        {
            ResponseDto? responseDto = await _patientService.GetPatientByIdAsync(patientId);
            if (responseDto != null && responseDto.IsSuccess)
            {
                PatientDto? patientDto = JsonConvert.DeserializeObject<PatientDto>(Convert.ToString(responseDto.Result));
                if (patientDto != null)
                {
                    return View(new UpdatePatientDto
                    {
                        PatientId = patientId,
                        Name = patientDto.Name,
                        LastName = patientDto.LastName,
                        DateOfBirth = patientDto.DateOfBirth,
                        PhoneNumber = patientDto.PhoneNumber,
                        Email = patientDto.Email
                    });
                }
                else
                {
                    TempData["error"] = "Paciente no encontrado.";
                }
            }
            else
            {
                TempData["error"] = responseDto?.Message ?? "Error al obtener el paciente.";
            }

            return RedirectToAction(nameof(PatientIndex));
        }

        [HttpPost]
        public async Task<IActionResult> PatientEdit(UpdatePatientDto patientDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto responseDto = await _patientService.UpdatePatientAsync(patientDto);
                if (responseDto != null && responseDto.IsSuccess)
                {
                    TempData["success"] = responseDto.Message ?? "Paciente actualizado correctamente.";
                    return RedirectToAction(nameof(PatientIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message ?? "Error al actualizar el paciente.";
                }
            }
            return View(patientDto);
        }

        #endregion
    }
}

CitasMedicas.Web/Controllers/SpecialtyController.cs
using CitasMedicas.Web.Models;
using CitasMedicas.Web.Models.Specialty;
using CitasMedicas.Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CitasMedicas.Web.Controllers
{
    public class SpecialtyController : Controller
    {
        private readonly ISpecialtyService _specialtyService;
        public SpecialtyController(ISpecialtyService specialtyService)
        {
            _specialtyService = specialtyService;
        }

        [HttpGet]
        public async Task<IActionResult> SpecialtyIndex()
        {
            List<SpecialtyDto>? specialtyList = new();
            ResponseDto? responseDto = await _specialtyService.GetSpecialtiesAsync();

            if (responseDto != null && responseDto.IsSuccess)
            {
                specialtyList = JsonConvert.DeserializeObject<List<SpecialtyDto>>(Convert.ToString(responseDto.Result));
            }
            else
            {
                TempData["error"] = responseDto?.Message ?? "Error al obtener las especialidades.";
            }

            return View(specialtyList);
        }

        #region Create Specialty

        [HttpGet]
        public async Task<IActionResult> SpecialtyCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SpecialtyCreate(CreateSpecialtyDto specialtyDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto responseDto = await _specialtyService.CreateSpecialtyAsync(specialtyDto);
                if (responseDto != null && responseDto.IsSuccess)
                {
                    TempData["success"] = responseDto.Message ?? "Especialidad creada correctamente.";
                    return RedirectToAction(nameof(SpecialtyIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message ?? "Error al crear la especialidad.";
                }
            }
            return View(specialtyDto);
        }

        #endregion

        #region Update Specialty

        [HttpGet]
        public async Task<IActionResult> SpecialtyEdit(int specialtyId)
        {
            ResponseDto? responseDto = await _specialtyService.GetSpecialtyByIdAsync(specialtyId);
            if (responseDto != null && responseDto.IsSuccess)
            {
                SpecialtyDto? specialtyDto = JsonConvert.DeserializeObject<SpecialtyDto>(Convert.ToString(responseDto.Result));
                if (specialtyDto != null)
                {
                    return View(new UpdateSpecialtyDto
                    {
                        SpecialtyId = specialtyId,
                        Name = specialtyDto.Name
                    });

                }
                else
                {
                    TempData["error"] = "Especialidad no encontrada.";
                }
            }
            else
            {
                TempData["error"] = responseDto?.Message ?? "Error al obtener el producto.";
            }

            return RedirectToAction(nameof(SpecialtyIndex));
        }

        [HttpPost]
        public async Task<IActionResult> SpecialtyEdit(UpdateSpecialtyDto specialtyDto)
        {
            if (ModelState.IsValid)
            {
                ResponseDto responseDto = await _specialtyService.UpdateSpecialtyAsync(specialtyDto);
                if (responseDto != null && responseDto.IsSuccess)
                {
                    TempData["success"] = responseDto.Message ?? "Especialidad actualizada correctamente.";
                    return RedirectToAction(nameof(SpecialtyIndex));
                }
                else
                {
                    TempData["error"] = responseDto?.Message ?? "Error al actualizar la especialidad.";
                }
            }
            return View(specialtyDto);
        }

        #endregion
    }
}

CitasMedicas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CitasMedicas.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasMedicas.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CitasMedicas.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="PatientIndex">Pacientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="DoctorIndex">Médicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Specialty" asp-action="SpecialtyIndex">Especialidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="AppointmentIndex">Citas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CitasMedicas.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>